    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ydtt-prod-net

  redis:
    image: redis:7-alpine
    container_name: ydtt-redis
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ydtt-prod-net

  celery:
    image: ${IMAGE_TAG}
    container_name: ydtt-celery
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - db
      - redis
    command: celery -A app.tasks.celery_app worker --loglevel=info
    networks:
      - ydtt-prod-net

volumes:
  postgres_data:
  redis_data:


networks:
  ydtt-prod-net:
    driver: bridge
